name: Selenium E2E test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    resources:
      limits:
        memory: 8GB  # Specify memory limit to avoid resource exhaustion

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      # Optional: Print environment information for debugging
      - name: Print Environment Info
        run: env

      - name: Run Test with Retry
        run: |
          for i in {1..3}; do mvn clean test -Dmaven.test.failure.ignore=true -Dhttp.timeout=30000 && break || sleep 30; done

      - name: Get Allure history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history